import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _values = {
    'en': {
      'app_name': 'BhandarX',
      'home': 'Home',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'profile': 'Profile',
      'workspace': 'Workspace',
      'logout': 'Logout',
      'dark_mode': 'Dark mode',
      'dark_mode_sub': 'Use the dark slate mobile theme',
      'push_notifications': 'Push notifications',
      'push_notifications_sub': 'Receive operational alerts on mobile',
      'email_alerts': 'Email alerts',
      'email_alerts_sub': 'Keep account notices enabled by email',
      'language': 'Language',
      'language_sub': 'English / Nepali',
      'english': 'English',
      'nepali': 'Nepali',
      'welcome_back': 'Welcome back',
      'quick_access':
          'Quick access to profile, notifications, and account preferences.',
      'my_profile': 'My Profile',
      'change_password': 'Change Password',
      'login': 'Login',
      'register': 'Register',
      'forgot_password': 'Forgot Password',
      'reset_password': 'Reset Password',
      'create_account': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'full_name': 'Full name',
      'cancel': 'Cancel',
      'save': 'Save',
      'search': 'Search',
      'all': 'All',
      'read': 'Read',
      'unread': 'Unread',
      'mark_all_read': 'Mark all read',
      'user_dashboard': 'User Dashboard',
      'notifications_empty': 'No notifications found',
      'login_subtitle':
          'Log in to your BhandarX account and continue your work.',
      'login_helper': 'Inventory on web. Account and notifications on mobile.',
      'enter_password': 'Enter your password',
      'new_to_bhandarx': 'New to BhandarX?',
      'register_subtitle':
          'Set up your BhandarX mobile account for profile and alerts.',
      'register_helper':
          'Use the same green-first identity as your web application.',
      'confirm_password': 'Confirm password',
      'permission_required': 'Permission Required',
      'permission_denied_message':
          'This feature requires camera or media permission. Please enable it in app settings.',
      'open_settings': 'Open Settings',
      'take_photo': 'Take photo',
      'choose_from_gallery': 'Choose from gallery',
      'workspace_title': 'User Workspace',
      'unauthorized_role': 'Unauthorized Role',
      'employee_only_workspace':
          'This mobile workspace is employee-only. Please login with an employee account.',
      'search_stock_details': 'Search, stock level, details',
      'view_add_edit_profiles': 'View, add, edit profiles',
      'create_sales_update_payment': 'Create sales and update payment',
      'history_and_details': 'History and details',
      'products_page': 'Products',
      'low_stock': 'Low Stock',
      'out_of_stock': 'Out Of Stock',
      'search_name_sku': 'Search by name, SKU...',
      'search_btn': 'Search',
      'no_products_found': 'No products found',
      'product_detail': 'Product Detail',
      'customers_page': 'Customers',
      'customer_detail': 'Customer Detail',
      'create_btn': 'Create',
      'create_customer': 'Create Customer',
      'edit_customer': 'Edit Customer',
      'name': 'Name',
      'phone': 'Phone',
      'address': 'Address',
      'customer_type': 'Customer Type',
      'name_phone_required': 'Name and phone are required',
      'valid_phone_required': 'Please enter a valid phone number',
      'valid_email_required': 'Please enter a valid email address',
      'sales_page': 'Sales',
      'new_sale': 'New Sale',
      'create_sale': 'Create Sale',
      'select_customer_product': 'Select customer and product/SKU',
      'enter_valid_qty_price': 'Enter valid quantity and price',
      'selected_product_out_stock': 'Selected product is out of stock',
      'product_id_missing':
          'Product ID missing. Select product from list or use valid SKU.',
      'available_stock': 'Available stock',
      'sale_detail': 'Sale Detail',
      'update_payment': 'Update Payment',
      'update': 'Update',
      'only_items_available':
          'Only {count} item(s) available for selected product',
      'transactions_page': 'Transactions',
      'transaction_detail': 'Transaction Detail',
      'recent_summary': 'Recent & Summary',
      'transaction_insights': 'Transaction Insights',
      'unable_load_insights': 'Unable to load insights',
      'recent_transactions': 'Recent Transactions',
      'no_recent_transactions': 'No recent transactions',
      'summary': 'Summary',
      'total_transactions': 'Total Transactions',
      'total_in': 'Total In',
      'total_out': 'Total Out',
      'failed_to_load': 'Failed to load',
      'no_items_found': 'No items found',
      'stock': 'Stock',
      'product_name': 'Product Name',
      'unit_price': 'Unit Price',
      'paid_amount': 'Paid Amount',
      'payment_method': 'Payment Method',
      'status': 'Status',
      'quantity': 'Quantity',
      'search_customers': 'Search customers',
      'search_sales': 'Search sales',
      'search_transactions': 'Search transactions',
      'clear_search': 'Clear search',
      'total_amount': 'Total Amount',
      'total_tax': 'Total Tax',
      'total_discount': 'Total Discount',
      'items': 'Items',
      'due_amount': 'Due Amount',
      'fill_full_payment': 'Fill full payment',
      'paid_cannot_exceed_total': 'Paid amount cannot exceed total amount',
      'dashboard_snapshot': 'Dashboard Snapshot',
      'today_sales': 'Today Sales',
      'pending_due': 'Pending/Due',
      'low_stock_count': 'Low Stock',
      'sales_trend_7d': 'Sales Trend (7 days)',
      'payment_split': 'Payment Split',
      'stock_health': 'Stock Health',
      'in_stock': 'In Stock',
      'all_time': 'All',
      'today': 'Today',
      'last_7_days': '7 Days',
      'last_30_days': '30 Days',
      'saved_offline_will_sync': 'Saved offline. Will sync automatically.',
      'offline_data_synced': 'Offline data synced: {count}',
      'sale_saved': 'Sale saved',
      'customer_saved': 'Customer saved',
      'qr': 'QR',
      'pay_by_qr': 'Pay By QR',
      'show_qr': 'Show QR',
      'scan_qr_to_pay': 'Scan this QR to complete payment',
      'mark_qr_paid': 'Mark QR Paid',
      'qr_payment_ready': 'QR payment amount set',
      'retail': 'Retail',
      'wholesale': 'Wholesale',
      'corporate': 'Corporate',
      'cash': 'Cash',
      'card': 'Card',
      'bank_transfer': 'Bank Transfer',
      'credit': 'Credit',
      'enter_valid_amount': 'Enter a valid amount',
      'add': 'Add',
      'sale': 'Sale',
      'paid': 'Paid',
      'pending': 'Pending',
      'partial': 'Partial',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
    },
    'ne': {
      'app_name': 'भण्डारएक्स',
      'home': 'होम',
      'settings': 'सेटिङ',
      'notifications': 'सूचना',
      'profile': 'प्रोफाइल',
      'workspace': 'वर्कस्पेस',
      'logout': 'लगआउट',
      'dark_mode': 'डार्क मोड',
      'dark_mode_sub': 'गाढा स्लेट मोबाइल थिम प्रयोग गर्नुहोस्',
      'push_notifications': 'पुस सूचना',
      'push_notifications_sub': 'मोबाइलमा सञ्चालन सम्बन्धी सूचना पाउनुहोस्',
      'email_alerts': 'इमेल सूचना',
      'email_alerts_sub': 'इमेलमार्फत सूचना सक्षम राख्नुहोस्',
      'language': 'भाषा',
      'language_sub': 'अंग्रेजी / नेपाली',
      'english': 'अंग्रेजी',
      'nepali': 'नेपाली',
      'welcome_back': 'फेरि स्वागत छ',
      'quick_access': 'प्रोफाइल, सूचना र खाता प्राथमिकतामा छिटो पहुँच।',
      'my_profile': 'मेरो प्रोफाइल',
      'change_password': 'पासवर्ड परिवर्तन',
      'login': 'लगइन',
      'register': 'दर्ता',
      'forgot_password': 'पासवर्ड बिर्सनुभयो?',
      'reset_password': 'पासवर्ड रिसेट',
      'create_account': 'खाता बनाउनुहोस्',
      'email': 'इमेल',
      'password': 'पासवर्ड',
      'full_name': 'पूरा नाम',
      'cancel': 'रद्द',
      'save': 'सुरक्षित',
      'search': 'खोज्नुहोस्',
      'all': 'सबै',
      'read': 'पढिएको',
      'unread': 'नपढिएको',
      'mark_all_read': 'सबै पढिएको बनाउनुहोस्',
      'user_dashboard': 'प्रयोगकर्ता ड्यासबोर्ड',
      'notifications_empty': 'कुनै सूचना फेला परेन',
      'login_subtitle':
          'आफ्नो भण्डारएक्स खातामा लगइन गरेर काम जारी राख्नुहोस्।',
      'login_helper': 'इनभेन्टरी वेबमा। खाता र सूचनाहरू मोबाइलमा।',
      'enter_password': 'आफ्नो पासवर्ड लेख्नुहोस्',
      'new_to_bhandarx': 'भण्डारएक्समा नयाँ हुनुहुन्छ?',
      'register_subtitle':
          'प्रोफाइल र सूचनाका लागि भण्डारएक्स मोबाइल खाता सेटअप गर्नुहोस्।',
      'register_helper':
          'तपाईंको वेब अनुप्रयोगको जस्तै हरियो-केन्द्रित पहिचान प्रयोग गर्नुहोस्।',
      'confirm_password': 'पासवर्ड पुष्टि गर्नुहोस्',
      'permission_required': 'अनुमति आवश्यक छ',
      'permission_denied_message':
          'यो सुविधा प्रयोग गर्न क्यामेरा वा मिडिया अनुमति आवश्यक छ। कृपया एप सेटिङमा अनुमति दिनुहोस्।',
      'open_settings': 'सेटिङ खोल्नुहोस्',
      'take_photo': 'फोटो खिच्नुहोस्',
      'choose_from_gallery': 'ग्यालरीबाट छान्नुहोस्',
      'workspace_title': 'प्रयोगकर्ता कार्यक्षेत्र',
      'unauthorized_role': 'अनधिकृत भूमिका',
      'employee_only_workspace':
          'यो मोबाइल कार्यक्षेत्र कर्मचारीका लागि मात्र हो। कृपया कर्मचारी खाताबाट लगइन गर्नुहोस्।',
      'search_stock_details': 'खोज, स्टक स्तर, विवरण',
      'view_add_edit_profiles': 'हेर्नुहोस्, थप्नुहोस्, सम्पादन गर्नुहोस्',
      'create_sales_update_payment':
          'बिक्री बनाउनुहोस् र भुक्तानी अद्यावधिक गर्नुहोस्',
      'history_and_details': 'इतिहास र विवरण',
      'products_page': 'उत्पादनहरू',
      'low_stock': 'कम स्टक',
      'out_of_stock': 'स्टक सकिएको',
      'search_name_sku': 'नाम, SKU बाट खोज्नुहोस्...',
      'search_btn': 'खोज',
      'no_products_found': 'कुनै उत्पादन फेला परेन',
      'product_detail': 'उत्पादन विवरण',
      'customers_page': 'ग्राहकहरू',
      'customer_detail': 'ग्राहक विवरण',
      'create_btn': 'सिर्जना',
      'create_customer': 'ग्राहक सिर्जना',
      'edit_customer': 'ग्राहक सम्पादन',
      'name': 'नाम',
      'phone': 'फोन',
      'address': 'ठेगाना',
      'customer_type': 'ग्राहक प्रकार',
      'name_phone_required': 'नाम र फोन आवश्यक छ',
      'valid_phone_required': 'कृपया मान्य फोन नम्बर प्रविष्ट गर्नुहोस्',
      'valid_email_required': 'कृपया मान्य इमेल ठेगाना प्रविष्ट गर्नुहोस्',
      'sales_page': 'बिक्री',
      'new_sale': 'नयाँ बिक्री',
      'create_sale': 'बिक्री सिर्जना',
      'select_customer_product': 'ग्राहक र उत्पादन/SKU छान्नुहोस्',
      'enter_valid_qty_price': 'मान्य मात्रा र मूल्य प्रविष्ट गर्नुहोस्',
      'selected_product_out_stock': 'छानिएको उत्पादन स्टकमा छैन',
      'product_id_missing':
          'उत्पादन आईडी भेटिएन। सूचीबाट उत्पादन छान्नुहोस् वा मान्य SKU प्रयोग गर्नुहोस्।',
      'available_stock': 'उपलब्ध स्टक',
      'sale_detail': 'बिक्री विवरण',
      'update_payment': 'भुक्तानी अद्यावधिक',
      'update': 'अद्यावधिक',
      'only_items_available':
          'छानिएको उत्पादनका लागि {count} वस्तु मात्र उपलब्ध छन्',
      'transactions_page': 'लेनदेनहरू',
      'transaction_detail': 'लेनदेन विवरण',
      'recent_summary': 'हालका र सारांश',
      'transaction_insights': 'लेनदेन अन्तर्दृष्टि',
      'unable_load_insights': 'अन्तर्दृष्टि लोड गर्न सकेन',
      'recent_transactions': 'हालका लेनदेनहरू',
      'no_recent_transactions': 'हालका लेनदेन छैनन्',
      'summary': 'सारांश',
      'total_transactions': 'कुल लेनदेन',
      'total_in': 'कुल जम्मा',
      'total_out': 'कुल निकासी',
      'failed_to_load': 'लोड गर्न असफल',
      'no_items_found': 'कुनै वस्तु फेला परेन',
      'stock': 'स्टक',
      'product_name': 'उत्पादन नाम',
      'unit_price': 'एकाइ मूल्य',
      'paid_amount': 'तिरेको रकम',
      'payment_method': 'भुक्तानी विधि',
      'status': 'स्थिति',
      'quantity': 'मात्रा',
      'search_customers': 'ग्राहक खोज्नुहोस्',
      'search_sales': 'बिक्री खोज्नुहोस्',
      'search_transactions': 'लेनदेन खोज्नुहोस्',
      'clear_search': 'खोज खाली गर्नुहोस्',
      'total_amount': 'कुल रकम',
      'total_tax': 'कुल कर',
      'total_discount': 'कुल छुट',
      'items': 'वस्तुहरू',
      'due_amount': 'बाँकी रकम',
      'fill_full_payment': 'पूरा भुक्तानी राख्नुहोस्',
      'paid_cannot_exceed_total': 'तिरेको रकम कुल रकमभन्दा बढी हुन सक्दैन',
      'dashboard_snapshot': 'ड्यासबोर्ड स्न्यापसट',
      'today_sales': 'आजको बिक्री',
      'pending_due': 'बाँकी/उधार',
      'low_stock_count': 'कम स्टक',
      'sales_trend_7d': 'बिक्री प्रवृत्ति (७ दिन)',
      'payment_split': 'भुक्तानी विभाजन',
      'stock_health': 'स्टक अवस्था',
      'in_stock': 'स्टकमा',
      'all_time': 'सबै',
      'today': 'आज',
      'last_7_days': '७ दिन',
      'last_30_days': '३० दिन',
      'saved_offline_will_sync': 'अफलाइन सुरक्षित गरियो। इन्टरनेट आएपछि सिङ्क हुन्छ।',
      'offline_data_synced': 'अफलाइन डाटा सिङ्क भयो: {count}',
      'sale_saved': 'बिक्री सुरक्षित भयो',
      'customer_saved': 'ग्राहक सुरक्षित भयो',
      'qr': 'QR',
      'pay_by_qr': 'QR बाट तिर्नुहोस्',
      'show_qr': 'QR देखाउनुहोस्',
      'scan_qr_to_pay': 'भुक्तानी गर्न यो QR स्क्यान गर्नुहोस्',
      'mark_qr_paid': 'QR भुक्तानी भएको चिन्ह लगाउनुहोस्',
      'qr_payment_ready': 'QR भुक्तानी रकम सेट गरियो',
      'retail': 'खुद्रा',
      'wholesale': 'थोक',
      'corporate': 'कर्पोरेट',
      'cash': 'नगद',
      'card': 'कार्ड',
      'bank_transfer': 'बैंक ट्रान्सफर',
      'credit': 'उधार',
      'enter_valid_amount': 'कृपया मान्य रकम प्रविष्ट गर्नुहोस्',
      'add': 'थप्नुहोस्',
      'sale': 'बिक्री',
      'paid': 'तिरेको',
      'pending': 'बाँकी',
      'partial': 'आंशिक',
      'completed': 'पूरा',
      'cancelled': 'रद्द',
    },
  };

  String tr(String key) {
    return _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;
  }

  String formatNumber(dynamic value) {
    if (value is num) {
      return NumberFormat.compact(locale: locale.languageCode).format(value);
    }
    return value.toString();
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ne'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
